### ISSUE TITLE
helm-gcs fails to install when curl is not present but the install script succeeds

### ISSUE THREAD

**Issue by regner** [hayorov/helm-gcs#15]
Helm version: 2.13.0

```
Installing helm-gcs 0.2.0 ...
./scripts/install.sh: line 32: curl: not found
tar: can't open 'helm-gcs_0.2.0_Linux_x86_64.tar.gz': No such file or directory
helm-gcs 0.2.0 is correctly installed.
```

No curl in the container I am using so the script fails, however it seems to exit OK and report being installed correctly.

It would be great if the install script checked for curl and wget. I do have wget in the container.

**Comment by regner** [comment]
Huh, it seems the script does check for the existence of curl, so not sure whats up there.

**Comment by hayorov** [comment]
Hello @regner I'll check this issue. 

According to install.sh cURL or wget required.

```
# Download archive
if [ -n $(command -v curl) ]
then
    curl -sSL -O $url
elif [ -n $(command -v wget) ]
then
    wget -q $url
else
    echo "Need curl or wget"
    exit -1
fi
```

**Comment by ulzar** [comment]
Hey guys,

It seems like this error is due to the github url changing from nouney to hayorov.
If like me you installed helm before the change from nouney to hayorov, you're helm installer is corrupted.

**Inspection**
Go to cd /root/.helm/plugins/helm-gcs

In here you will see a file named `install.sh`
Open it.
You will see it is using the url https://api.github.com/repos/nouney/helm-gcs/releases/latest

If you run the command in the script, you should see the following:
curl --silent https://api.github.com/repos/nouney/helm-gcs/releases/latest
{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/109006561/releases/latest",
  "documentation_url": "https://developer.github.com/v3/#http-redirects"
}


**Fix:**
A) Open the file:
/root/.helm/plugins/helm-gcs/install.sh

B) Replace the following command
curl --silent https://api.github.com/repos/nouney/helm-gcs/releases/latest
by
curl --silent https://api.github.com/repos/hayorov/helm-gcs/releases/latest

C) Then remove the corrupted install plugin by entering the following command:
helm plugin remove gcs

D) Then install properly the helm gcs plugin with:
helm plugin install https://github.com/hayorov/helm-gcs --version 0.1.4

**Conclusion**
It fixed my error. I hope it will some of you in the same situation.
