### ISSUE TITLE
can't install latest version

### ISSUE THREAD

**Issue by AlbyIanna** [hayorov/helm-gcs#39]
I'm trying to install the latest stable version (currently `0.3.1`) but when I run this command
```
helm plugin install https://github.com/hayorov/helm-gcs
```
it seems to install version `0.3.0`. This is the output I get
```
Installing helm-gcs 0.3.0 ...
x LICENSE
x README.md
x helm-gcs
helm-gcs 0.3.0 is correctly installed.

Init a new repository:
  helm gcs init gs://bucket/path

Add your repository to Helm:
  helm repo add repo-name gs://bucket/path

Push a chart to your repository:
  helm gcs push chart.tar.gz repo-name

Update Helm cache:
  helm repo update

Get your chart:
  helm fetch repo-name/chart

Installed plugin: gcs
```

The same thing happens if I try to install it specifying a version
```
helm plugin install https://github.com/hayorov/helm-gcs --version 0.3.1
```

**Comment by arthurk** [comment]
Same happens for me:

```
$ helm plugin install https://github.com/hayorov/helm-gcs --version 0.3.1
Installing helm-gcs 0.3.0 ...
helm-gcs 0.3.0 is correctly installed.
```

Removing helm plugin cache and re-installing without version flag works:

```
rm -rf ~/.cache/helm/plugins/
helm plugin install https://github.com/hayorov/helm-gcs
Installing helm-gcs 0.3.1 ...
helm-gcs 0.3.1 is correctly installed.

```

**Comment by endorama** [comment]
Hello @hayorov, we are impacted by this too. 
I've just a basic understanding of how helm plugin system works, if you are able to take a look and help us debug I'm willing to help in resolution or escalation to helm (in case this is not an issue with the plugin itself but affects helm as a whole).
Thanks!

**Comment by hayorov** [comment]
I'm going to investigate the problem this week. Currently, I'm on PTO and my availability is limited.

**Comment by endorama** [comment]
@hayorov no problem, I'll happily wait! If you can give some hint where to look I'll be happy to have a look.

**Comment by masci** [comment]
@hayorov the problem is tag [`0.3.4`](https://github.com/hayorov/helm-gcs/commits/0.3.4) points to commit [c1e210f](https://github.com/hayorov/helm-gcs/commit/c1e210ff45e9ce31a0998106b474323f55aee062) where the field `version` in `plugin.yaml` [is wrongly set to 0.3.1](https://github.com/hayorov/helm-gcs/blob/c1e210ff45e9ce31a0998106b474323f55aee062/plugin.yaml#L2).

If you could move the tag 0.3.4 to [6aa25](https://github.com/hayorov/helm-gcs/commit/6aa25d0634cd917549cc3d914b1bd413e90727a4) or add a new 0.3.5, that would be great as currently there's no way to install latest.

**Comment by hayorov** [comment]
@masci Oh, right! Forgot to push this fix in GH. Fixed. 0.3.4 points to https://github.com/hayorov/helm-gcs/commit/6aa25d0634cd917549cc3d914b1bd413e90727a4

Many thanks!
